=== ogcincubator/iliad-apis-features/checkin/transformers/json-to-json-feature/canonical.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://iliad/checkin/transformers/json-to-json-feature/canonical.schema.json",
  "title": "GeoJSON Feature",
  "type": "object",
  "required": ["type", "geometry", "properties"],
  "properties": {
    "type": {"const": "Feature"},
    "id": {"type": ["string", "integer", "null"]},
    "geometry": {
      "type": "object",
      "required": ["type", "coordinates"],
      "properties": {
        "type": {"enum": ["Point", "MultiPoint", "LineString", "MultiLineString", "Polygon", "MultiPolygon"]},
        "coordinates": {}
      }
    },
    "properties": {"type": ["object", "null"]}
  }
}

=== ogcincubator/iliad-apis-features/_sources/apkg-record/examples/commandlinetool-virtual-choreographies.json
{
  "geometry": {
    "coordinates": [
      [
        [
          -180.0,
          -90.0
        ],
        [
          180.0,
          -90.0
        ],
        [
          180.0,
          90.0
        ],
        [
          -180.0,
          90.0
        ],
        [
          -180.0,
          -90.0
        ]
      ]
    ],
    "type": "Polygon"
  },
  "type": "Feature",
  "properties": {
    "outputs": [
      {
        "format": "edam:format_3464",
        "id": "vc",
        "type": "File"
      },
      {
        "format": "edam:format_3464",
        "id": "recipe",
        "type": "File"
      }
    ],
    "programming_language": "python",
    "keywords": [
      "wp6-tools",
      "choreographies",
      "virtual-choreographies"
    ],
    "inputs": [
      {
        "id": "template",
        "type": "File?"
      },
      {
        "id": "template_url",
        "type": "string?"
      },
      {
        "id": "dataset",
        "type": "File"
      }
    ],
    "description": "Generator of virtual choreographies",
    "maintainer": [
      {
        "name": "Vitor Cavaleiro",
        "email": "vitor.cavaleiro@inesctec.pt"
      }
    ],
    "sdPublisher": [
      {
        "name": "Application Package Registry",
        "class": "Organization",
        "url": "https://iliad-registry.inesctec.pt"
      }
    ],
    "temporal_coverage": null,
    "contributor": [
      {
        "name": "Miguel Correia",
        "email": "miguel.r.correia@inesctec.pt"
      }
    ],
    "spatial_coverage": {
      "geo": {
        "box": "-90 -180 90 180"
      },
      "class": "schema:GeoShape"
    },
    "id": "virtual-choreographies-generator",
    "software_version": "0.2.1",
    "class": "CommandLineTool",
    "latest": true,
    "identifier": "urn:apkg:tool:inesctec:pt:virtual-choreographies-generator:0.2.1",
    "citation": null,
    "date_created": "2025-05-26T10:06:27Z",
    "author": [
      {
        "name": "Fernando Cassola",
        "email": "fernando.c.marques@inesctec.pt"
      },
      {
        "name": "Vitor Cavaleiro",
        "email": "vitor.cavaleiro@inesctec.pt"
      }
    ],
    "sdDatePublished": "2025-06-11T14:23:07.233541Z",
    "url": "https://iliad-registry.inesctec.pt/collections/apkg/items/urn:apkg:tool:inesctec:pt:virtual-choreographies-generator:0.2.1?f=cwl",
    "license": null,
    "code_repository": "https://pipe-drive.inesctec.pt/application-packages/tools/virtual-choreographies-generator/virtual_choreographies_generator_0_2_1.cwl",
    "source_organization": [
      {
        "address": {
          "address_country": "PT"
        },
        "name": "INESCTEC",
        "url": "https://inesctec.pt"
      }
    ],
    "name": "virtual-choreographies-generator",
    "cwl": "cwlVersion: v1.2\n$namespaces:\n  s: https://schema.org/\n  edam: http://edamontology.org/\n$graph:\n- class: CommandLineTool\n  id: virtual-choreographies-generator\n  baseCommand: python\n  arguments:\n  - /opt/src/command.py\n  - valueFrom: $( inputs.dataset )\n  - valueFrom: $( inputs.template || inputs.template_url || '/opt/templates/template.json')\n  inputs:\n    template:\n      type: File?\n    template_url:\n      type: string?\n    dataset:\n      type: File\n  outputs:\n    vc:\n      format: edam:format_3464\n      type: File\n      outputBinding:\n        glob: vc.json\n    recipe:\n      format: edam:format_3464\n      type: File\n      outputBinding:\n        glob: recipe.json\n  requirements:\n    NetworkAccess:\n      networkAccess: true\n    ResourceRequirement: {}\n    InlineJavascriptRequirement: {}\n    DockerRequirement:\n      dockerPull: iliad-repository.inesctec.pt/virtual-choreographies-generator:0.2.1\n  s:name: virtual-choreographies-generator\n  s:description: Generator of virtual choreographies\n  s:keywords:\n  - wp6-tools\n  - choreographies\n  - virtual-choreographies\n  s:programmingLanguage: python\n  s:softwareVersion: 0.2.1\n  s:producer:\n    class: s:Organization\n    s:name: INESCTEC\n    s:url: https://inesctec.pt\n    s:address:\n      class: s:PostalAddress\n      s:addressCountry: PT\n  s:sourceOrganization:\n  - class: s:Organization\n    s:name: INESCTEC\n    s:url: https://inesctec.pt\n    s:address:\n      class: s:PostalAddress\n      s:addressCountry: PT\n  s:author:\n  - class: s:Person\n    s:name: Fernando Cassola\n    s:email: fernando.c.marques@inesctec.pt\n  - class: s:Person\n    s:name: Vitor Cavaleiro\n    s:email: vitor.cavaleiro@inesctec.pt\n  s:maintainer:\n  - class: s:Person\n    s:name: Vitor Cavaleiro\n    s:email: vitor.cavaleiro@inesctec.pt\n  s:contributor:\n  - class: s:Person\n    s:name: Miguel Correia\n    s:email: miguel.r.correia@inesctec.pt\n  s:codeRepository: https://pipe-drive.inesctec.pt/application-packages/tools/virtual-choreographies-generator/virtual_choreographies_generator_0_2_1.cwl\n  s:dateCreated: '2025-05-26T10:06:27Z'\n  s:sdDatePublished: '2025-06-11T14:23:07.233541Z'\n  s:sdPublisher:\n    class: Organization\n    name: Application Package Registry\n    url: https://iliad-registry.inesctec.pt\n  s:identifier: urn:apkg:tool:inesctec:pt:virtual-choreographies-generator:0.2.1\n",
    "producer": [
      {
        "address": {
          "address_country": "PT"
        },
        "name": "INESCTEC",
        "url": "https://inesctec.pt"
      }
    ],
    "family": "urn:apkg:tool:inesctec:pt:virtual-choreographies-generator"
  },
  "id": "urn:apkg:tool:inesctec:pt:virtual-choreographies-generator:0.2.1"
}

=== ogcincubator/iliad-apis-features/_sources/apkg-record/examples/commandlinetool-wo-data-filter.json
{
  "geometry": {
    "coordinates": [
      [
        [
          -180.0,
          -90.0
        ],
        [
          180.0,
          -90.0
        ],
        [
          180.0,
          90.0
        ],
        [
          -180.0,
          90.0
        ],
        [
          -180.0,
          -90.0
        ]
      ]
    ],
    "type": "Polygon"
  },
  "type": "Feature",
  "properties": {
    "outputs": [
      {
        "format": "edam:format_3752",
        "doc": "result file",
        "id": "results",
        "type": "File",
        "fileFormat": "text/csv"
      },
      {
        "format": "edam:format_3464",
        "doc": "metadata description",
        "id": "metadata",
        "type": "File"
      }
    ],
    "programming_language": "python",
    "keywords": [
      "meloa",
      "wavy",
      "ocean",
      "dataset",
      "filter"
    ],
    "inputs": [
      {
        "doc": "CSV endpoint",
        "id": "url",
        "type": "string"
      },
      {
        "doc": "baseline",
        "id": "base",
        "type": "float"
      },
      {
        "default": "gt",
        "doc": "operation to apply",
        "id": "op",
        "type": "string?"
      }
    ],
    "description": "WO csv filter",
    "maintainer": null,
    "sdPublisher": [
      {
        "name": "Application Package Registry",
        "class": "Organization",
        "url": "https://iliad-registry.inesctec.pt"
      }
    ],
    "temporal_coverage": null,
    "contributor": null,
    "spatial_coverage": {
      "geo": {
        "box": "-90 -180 90 180"
      },
      "class": "schema:GeoShape"
    },
    "id": "wo-data-filter",
    "software_version": "0.1.0",
    "class": "CommandLineTool",
    "latest": true,
    "identifier": "urn:apkg:tool:inesctec:pt:wo-data-filter:0.1.0",
    "citation": null,
    "date_created": "2025-05-12T15:28:16Z",
    "author": [
      {
        "name": "Miguel Correia",
        "email": "miguel.r.correia@inesctec.pt"
      }
    ],
    "sdDatePublished": "2025-06-11T14:22:57.804762Z",
    "url": "https://iliad-registry.inesctec.pt/collections/apkg/items/urn:apkg:tool:inesctec:pt:wo-data-filter:0.1.0?f=cwl",
    "license": null,
    "code_repository": "https://pipe-drive.inesctec.pt/application-packages/tools/wo-data-processing/wo_data_processing_0_1_0.cwl",
    "source_organization": [
      {
        "address": {
          "address_country": "PT"
        },
        "name": "INESCTEC",
        "url": "https://inesctec.pt"
      }
    ],
    "name": "wo-data-filter",
    "cwl": "cwlVersion: v1.2\n$namespaces:\n  s: https://schema.org/\n  edam: http://edamontology.org/\n$graph:\n- class: CommandLineTool\n  id: wo-data-filter\n  baseCommand: python\n  arguments:\n  - /opt/script.py\n  - --url\n  - valueFrom: $( inputs.url )\n  - --base\n  - valueFrom: $( inputs.base )\n  - valueFrom: $( function () { if (inputs.op) { return [\"--op\", inputs.op]; } else\n      { return []; } }())\n  inputs:\n    url:\n      type: string\n      doc: CSV endpoint\n    base:\n      type: float\n      doc: baseline\n    op:\n      type: string?\n      doc: operation to apply\n      default: gt\n  outputs:\n    results:\n      format: edam:format_3752\n      type: File\n      outputBinding:\n        glob: result/result.csv\n      doc: result file\n      s:fileFormat: text/csv\n    metadata:\n      format: edam:format_3464\n      type: File\n      outputBinding:\n        glob: result/metadata.json\n      doc: metadata description\n  requirements:\n    ResourceRequirement: {}\n    NetworkAccess:\n      networkAccess: true\n    InlineJavascriptRequirement: {}\n    DockerRequirement:\n      dockerPull: iliad-repository.inesctec.pt/wo-data-processing:0.1.0\n  s:name: wo-data-filter\n  s:description: WO csv filter\n  s:keywords:\n  - meloa\n  - wavy\n  - ocean\n  - dataset\n  - filter\n  s:programmingLanguage: python\n  s:softwareVersion: 0.1.0\n  s:producer:\n    class: s:Organization\n    s:name: INESCTEC\n    s:url: https://inesctec.pt\n    s:address:\n      class: s:PostalAddress\n      s:addressCountry: PT\n  s:sourceOrganization:\n  - class: s:Organization\n    s:name: INESCTEC\n    s:url: https://inesctec.pt\n    s:address:\n      class: s:PostalAddress\n      s:addressCountry: PT\n  s:author:\n  - class: s:Person\n    s:name: Miguel Correia\n    s:email: miguel.r.correia@inesctec.pt\n  s:codeRepository: https://pipe-drive.inesctec.pt/application-packages/tools/wo-data-processing/wo_data_processing_0_1_0.cwl\n  s:dateCreated: '2025-05-12T15:28:16Z'\n  s:sdDatePublished: '2025-06-11T14:22:57.804762Z'\n  s:sdPublisher:\n    class: Organization\n    name: Application Package Registry\n    url: https://iliad-registry.inesctec.pt\n  s:identifier: urn:apkg:tool:inesctec:pt:wo-data-filter:0.1.0\n",
    "producer": [
      {
        "address": {
          "address_country": "PT"
        },
        "name": "INESCTEC",
        "url": "https://inesctec.pt"
      }
    ],
    "family": "urn:apkg:tool:inesctec:pt:wo-data-filter"
  },
  "id": "urn:apkg:tool:inesctec:pt:wo-data-filter:0.1.0"
}
